issuer: https://localhost:5556/dex

storage:
  type: memory

web:
  https: 0.0.0.0:5556
  tlsCert: /etc/ssl/cert.pem
  tlsKey: /etc/ssl/key.pem

staticClients:
- id: stratus
  redirectURIs:
  - 'http://localhost:5173/auth/callback'
  name: 'Stratus App'
  secret: stratus-secret

enablePasswordDB: true
staticPasswords:
- email: "dani@example.com"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # "password"
  username: "dani"
  userID: "98b080b5-24e4-4b0f-979c-43a9c42e3c17"
